### ISSUE TITLE
Support for hcl_domino_standalone_provisioner v0.1.23

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Installer#118]
@MarkProminic is planning to release hcl_domino_standalone_provisioner v0.1.23 this week.  This has some more renames for the roles - @MarkProminic will report or discuss the changes when they are ready.

**Comment by piotrzarzycki21** [comment]
@MarkProminic in file [version.rb](https://github.com/STARTcloud/hcl_domino_standalone_provisioner/blob/main/hcl_domino_standalone_provisioner/version.rb) for provisioner 0.1.23 I still see version 0.1.22. Should I make PR?

**Comment by MarkProminic** [comment]
you should provide them, it was discussed that you give me that information so  that I can do verification tha the included installler is indeed meant for the task we are trying to run it through.

**Comment by MarkProminic** [comment]
There will be multiple versions.rb

PLease look at the contentes of the version.rb, Notice the name of of the Module. They are different, They must be included

**Comment by JoelProminic** [comment]
Currently we handle the [hash and version mapping](https://github.com/Moonshine-IDE/Super.Human.Installer/blob/3cce511670cf13b711ec8d5e74923947fd159bca/Source/superhuman/config/SuperHumanHashes.hx#L5) on the Super.Human.Installer side.  This should have been covered already by #76 .

**Comment by piotrzarzycki21** [comment]
Hey @MarkProminic after changing SHI I run vagrant up and this is what I'm getting. Could you please take a look. 

```
[SHI]:
---- Hosts.yml START ----
# core_provisioner_version: 0.2.8
# provisioner_name: hcl_domino_standalone_provisioner
# provisioner_version: 0.1.22
---
hosts:
  -
    settings:
      # Identifiers
      hostname: hcl
      domain: startcloud.com
      server_id: '6062'

      # Resources
      vcpus: 2
      memory: 8G

      # Console Access
      consoleport: 6062
      consolehost: 0.0.0.0
      show_console: false ## Some people have reported issues when VBox doesn't show the Console

      # Box information
      box: 'STARTcloud/debian12-server'
      box_url: 'https://vagrantcloud.com'
      box_version: 0.0.4

      # Provider Specific Settings
      provider-type: virtualbox
      os_type: 'Debian_64'
      firmware_type: UEFI

      # Setup Variables
      setup_wait: 300

      # Vagrant Configurations
      vagrant_user_private_key_path: ./id_rsa
      vagrant_user: startcloud #  startcloud
      vagrant_user_pass: STARTcloud24@! # 'STARTcloud24@!' 
      vagrant_insert_key: true
      ssh_forward_agent: true

    networks:
      # Future iteration may omit this to skip attaching a bridged adpater, the below block will need to be template unto itself
      - type: external
        address: 192.168.2.1
        netmask: 255.255.255.0
        gateway: 
        dhcp4: true
        dhcp6: false # false
        bridge: 
        mac: auto
        dns:
          - nameserver: 1.1.1.1
          - nameserver: 1.0.0.1

    provisioning:
      shell:
        enabled: false
        scripts:
          - './scripts/aliases.sh'

      ansible:
        enabled: true
        scripts:
          - local:
              - script: ansible/generate-playbook.yml
                ansible_python_interpreter: /usr/bin/python3
                compatibility_mode: 2.0
                install_mode: pip
                ssh_pipelining: true
                verbose: false
                remote_collections: true
              - script: ansible/playbook.yml
                ansible_python_interpreter: /usr/bin/python3
                compatibility_mode: 2.0
                install_mode: pip
                ssh_pipelining: true
                verbose: false
                remote_collections: true

    folders:
      - 
        description: "Disables VBoxSF, do not enable"
        map: .
        to: /vagrant
        type: virtualbox
        disabled: true
        automount: true
      -
        description: "Directory for Ansible Scripts"
        map: ./provisioners/ansible/
        to: /vagrant/ansible/
        type: rsync
        args:
          - '--verbose'
          - '--archive'
          - '--delete'
          - '-z'
          - '--copy-links'
      -
        description: "Directory for Application Installers"
        map: ./installers/
        to: /vagrant/installers/
        type: rsync
      -
        description: "Directory for Pre-Signed SSLs"
        map: ./ssls/
        to: /secure/
        type: rsync
      -
        description: "Directory for Server and User IDs"
        map: ./id-files/
        to: /id-files/
        type: rsync
        syncback: true

    vars:
      debug_all: true
      selfsigned_enabled: true
      haproxy_ssl_redirect: true
      
      # Domino Configuration Variables
      domino_organization: startcloud
      safe_notes_id: safe.ids
      domino_admin_notes_id_password: password
      generate_server_id_count: 0

      # Additional server options
      is_additional_server: false

      # Genesis Variables
      genesis_packages:
        - netmonitor
        - SuperHumanPortal

      # Domino Installer Variables
      domino_hash: 
      domino_major_version: 12
      domino_minor_version: 2
      domino_patch_version: 0

      # Domino fixpack Variables
      domino_fp_hash: 
      domino_server_installer_tar: Domino_12.0.2_Linux_English.tar
      domino_installer_fixpack_install: true
      domino_fixpack_version: FP2
      domino_server_fixpack_tar: Domino_1202FP2_Linux.tar

      # Domino Hotfix Variables
      domino_hf_hash: 
      domino_installer_hotfix_install: false
      domino_hotfix_version: 
      domino_server_hotfix_tar: 

      # Leap Variables
      leap_hash: 
      leap_archive: Leap-1.0.5.zip
      leap_version: 1.0.5

      # Nomad Web Variables
      nomadweb_hash: 
      nomadweb_archive: nomad-server-1.0.11-for-domino-12.0.2-linux.tgz
      nomadweb_version: 1.0.11

      # Traveler Variables
      #traveler_hash: null
      traveler_archive: Traveler_12.0.2FP1_Linux_ML.tar.gz
      traveler_base_version: 12.0.2
      traveler_fixpack_archive: 
      traveler_fixpack_version: 

      # Verse Variables
      #verse_hash: null
      verse_archive: HCL_Verse_3.0.0.zip
      verse_base_version: 3.0.0

      # AppDev Web Pack Variables
      #appdevpack_hash: null
      appdevpack_archive: domino-appdev-pack-1.0.15.tgz
      appdevpack_version: 1.0.15

      # Domino Rest API Variables
      #domino_rest_api_hash: null
      domino_rest_api_version: 
      domino_rest_api_archive: Domino_REST_API_V1.0.10_R12_Installer.zip

    roles:
      - name: startcloud.startcloud_roles.setup
      - name: startcloud.startcloud_roles.networking
        tags: always
      - name: startcloud.startcloud_roles.hostname
      - name: startcloud.startcloud_roles.dependencies
      - name: startcloud.startcloud_roles.service_user
      - name: startcloud.startcloud_roles.sdkman_install
      - name: startcloud.startcloud_roles.sdkman_java
      - name: startcloud.startcloud_roles.sdkman_maven
      - name: startcloud.startcloud_roles.sdkman_gradle
      - name: startcloud.startcloud_roles.ssl
       #- name: startcloud.hcl_roles.domino_reset 
      - name: startcloud.hcl_roles.domino_install
      - name: startcloud.hcl_roles.domino_vagrant_rest_api 
      - name: startcloud.hcl_roles.domino_service_nash
      - name: startcloud.hcl_roles.domino_java_config
      - name: startcloud.hcl_roles.domino_java_tools
      - name: startcloud.hcl_roles.domino_updatesite
      - name: startcloud.hcl_roles.domino_config 
      - name: startcloud.hcl_roles.domino_genesis
      - name: startcloud.hcl_roles.domino_genesis_applications
      - name: startcloud.hcl_roles.domino_cross_certify
      #- name: startcloud.hcl_roles.domino_java_app_example ## Uncomment Me to build your own Domino Java Servlet
      - name: startcloud.hcl_roles.domino_leap #startcloud.hcl_roles.domino_leap 
      - name: startcloud.hcl_roles.domino_nomadweb
      - name: startcloud.hcl_roles.domino_traveler 
      - name: startcloud.hcl_roles.domino_traveler_htmo 
      - name: startcloud.hcl_roles.domino_verse 
      - name: startcloud.hcl_roles.domino_appdevpack 
      - name: startcloud.hcl_roles.domino_rest_api ## Note to SHI devs, This should be called ROLE_DOMINO_RESTAPI, as this is different than startcloud.hcl_roles.domino_vagrant_rest_api
      - name: startcloud.hcl_roles.domino_vagrant_readme
        
        
      
      
      - name: startcloud.startcloud_roles.quick_start # - name: startcloud_quick_start
        tags: always
      - name: startcloud_haproxy
      - name: startcloud_vagrant_readme
      - name: startcloud.startcloud_roles.lockdown

---- Hosts.yml END ----
[SHI]: VirtualBox VM: { virtualBoxId => 6062--hcl.startcloud.com, serverId => 6062 }
[SHI]: Executing 'vagrant up' (provision:false)
[SHI]: 'vagrant up' started
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /Users/piotrzarzycki/Library/Application Support/SuperHumanInstallerDev/servers/demo-tasks/6062/core/Hosts.rb
Line number: 0
Message: undefined method `each'

            host['provisioning']['ansible']['playbooks'].each do |playbooks|
                                                        ^^^^^
[SHI]: 'vagrant up' stopped with exit code: 1, elapsed time: 00:00:02
```
