### ISSUE TITLE
domino_rest_api Fails Even Though Not Configured.

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Installer#144]
I tried to create a fresh standalone 0.1.23 instance today in Super.Human.Installer 1.2.0 on macOS (`Mac OS 13.6.7 | X86_64 | Cores:6 | RAM: 64GB | Vagrant 2.4.0 | VirtualBox 7.0.18`).  I configured only the Domino installer, with a fixpack and hotfix:

Hosts.yml:  

[2025_03_31__test-14.shi.com_Hosts.yml.zip](https://github.com/user-attachments/files/19542627/2025_03_31__test-14.shi.com_Hosts.yml.zip)

```
      # Domino Installer Variables
      domino_hash: 89a59f845d120055859a2c638809a75c
      domino_server_installer_tar: Domino_14.0_Linux_English.tar
      domino_major_version: 14
      domino_minor_version: 0
      domino_patch_version: 0

      # Domino fixpack Variables
      domino_fp_hash: 255cf7862db4b6bd9c0d3a4444bd064d
      domino_installer_fixpack_install: true
      domino_fixpack_version: FP3
      domino_server_fixpack_tar: Domino_1400FP3_Linux.tar

      # Domino Hotfix Variables
      domino_hf_hash: null
      domino_installer_hotfix_install: true
      domino_hotfix_version: null
      domino_server_hotfix_tar: 140FP3HF9-linux64.tar

...

      # Domino Rest API Variables
      #domino_rest_api_hash: null
      domino_rest_api_version: null
      domino_rest_api_archive: null

...

    roles:
      - name: startcloud.startcloud_roles.setup
      - name: startcloud.startcloud_roles.networking
        tags: always
      - name: startcloud.startcloud_roles.disks
      - name: startcloud.startcloud_roles.hostname
      - name: startcloud.startcloud_roles.dependencies
      - name: startcloud.startcloud_roles.mdns
      - name: startcloud.startcloud_roles.service_user
      - name: startcloud.startcloud_roles.sdkman_install
      - name: startcloud.startcloud_roles.sdkman_java
      - name: startcloud.startcloud_roles.sdkman_maven
      - name: startcloud.startcloud_roles.sdkman_gradle
      - name: startcloud.startcloud_roles.ssl
      - name: startcloud.hcl_roles.domino_reset
        vars:
          run_tasks: false
      - name: startcloud.hcl_roles.domino_install
      - name: startcloud.hcl_roles.domino_vagrant_rest_api
      - name: startcloud.hcl_roles.domino_service_nash
      - name: startcloud.hcl_roles.domino_java_config
      - name: startcloud.hcl_roles.domino_java_tools
      - name: startcloud.hcl_roles.domino_updatesite
      - name: startcloud.hcl_roles.domino_config 
      - name: startcloud.hcl_roles.domino_genesis
      - name: startcloud.hcl_roles.domino_genesis_applications
      - name: startcloud.hcl_roles.domino_cross_certify
      - name: startcloud.hcl_roles.domino_java_app_example
        vars:
          run_tasks: true
      - name: startcloud.hcl_roles.domino_oidc
        vars:
          run_tasks: true # Default to true
      - name: startcloud.hcl_roles.domino_leap
        vars:
          run_tasks: false
      - name: startcloud.hcl_roles.domino_traveler
        vars:
          run_tasks: false
      - name: startcloud.hcl_roles.domino_traveler_htmo
        vars:
          run_tasks: false
      - name: startcloud.hcl_roles.domino_verse
        vars:
          run_tasks: false
      - name: startcloud.hcl_roles.domino_appdevpack
        vars:
          run_tasks: false
      - name: startcloud.hcl_roles.domino_rest_api
        vars:
          run_tasks: false
      - name: startcloud.hcl_roles.domino_nomadweb
        vars:
          run_tasks: false
      - name: startcloud.hcl_roles.domino_jedi
        vars:
          run_tasks: true
      - name: startcloud.hcl_roles.domino_vagrant_readme
      - name: startcloud.startcloud_roles.quick_start
        tags: always
        vars:
          run_tasks: true
      - name: startcloud.startcloud_roles.haproxy
        vars:
          run_tasks: true
      - name: startcloud.startcloud_roles.vagrant_readme
        vars:
          run_tasks: true
      - name: startcloud.startcloud_roles.lockdown
        vars:
          run_tasks: true
```

However, the install failed on domino_rest_api, which was not enabled:

    [0;32m [started TASK: startcloud.hcl_roles.domino_rest_api : Checking if domino-rest-api is installed: {{ domino_rest_api_version }} on 2020--test-14.shi.com][0m
    [0;32m [started TASK: startcloud.hcl_roles.domino_rest_api : Creating installation directories for domino-rest-api on 2020--test-14.shi.com][0m
    [0;32m [started TASK: startcloud.hcl_roles.domino_rest_api : Checking if domino-rest-api installer is at domino-rest-api/archives/{{ domino_rest_api_archive }} on 2020--test-14.shi.com][0m
    [0;32m [started TASK: startcloud.hcl_roles.domino_rest_api : Downloading domino-rest-api from {{ domino_installer_base_url }} on 2020--test-14.shi.com][0m
    [0;32m [started TASK: startcloud.hcl_roles.domino_rest_api : Extracting domino-rest-api from {{ domino_rest_api_archive }} on 2020--test-14.shi.com][0m
    [0;32m [started TASK: startcloud.hcl_roles.domino_rest_api : Stopping Domino for Changes to take effect on 2020--test-14.shi.com][0m
    [0;32m [started TASK: startcloud.hcl_roles.domino_rest_api : Waiting for 30 seconds to let Domino fully shutdown on 2020--test-14.shi.com][0m
    [0;32m [started TASK: startcloud.hcl_roles.domino_rest_api : Installing Domino Rest API on 2020--test-14.shi.com][0m

    TASK [startcloud.hcl_roles.domino_rest_api : Installing Domino Rest API] *******
    [1;30mtask path: /vagrant/ansible_collections/startcloud/hcl_roles/roles/domino_rest_api/tasks/main.yml:76[0m
    [0;31mfatal: [2020--test-14.shi.com]: FAILED! => [0m
    [0;31m  msg: 'An unhandled exception occurred while templating ''{% if domino_rest_api_version is version(''1'', ''=='') %}restapiInstall.jar{% elif domino_rest_api_version is version(''1.0.9'', ''>='') %}restapiInstall-r{{ domino_major_version }}.jar{% else %}restapiInstall.jar{% endif %}''. Error was a <class ''ansible.errors.AnsibleFilterError''>, original message: Input version value cannot be empty'[0m

    PLAY RECAP *********************************************************************
    [0;31m2020--test-14.shi.com[0m      : [0;32mok=334 [0m [0;33mchanged=161 [0m unreachable=0    [0;31mfailed=1   [0m [0;36mskipped=264 [0m rescued=0    ignored=0   

    Ansible failed to complete successfully. Any error output should be
    visible above. Please fix these errors and try again.
    [SHI]: 'vagrant up' stopped with exit code: 1, elapsed time: 00:29:21

It looks like this might be a problem with the provisioners instead, so I'm tagging @MarkProminic.    I'm recreating the instance to see if that makes a difference.
