### ISSUE TITLE
Overriding Installers and Versions

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Installer#76]
When we tried to test with a newer version of NomadWeb (1.0.8), we got a crash (#75) with error using the old version number (1.0.6):

    TASK [domino-nomadweb : Extracting NomadWeb from nomad-server-1.0.6-for-domino-1202-linux.tgz] ***

    [2023-06-20 15:06:33][DEBUG][Source/superhuman/server/Server.hx:1147] [Server(8699)]: Vagrant up: fatal: [8699--demo.STARTcloud.com]: FAILED! => {"changed": false, "msg": "Source '/vagrant/installers/nomadweb/archives/nomad-server-1.0.6-for-domino-1202-linux.tgz' does not exist"}

This is because the installer name is [hard-coded](https://github.com/Moonshine-IDE/Super.Human.Installer/blob/019e59572e7a3f615f136b69cfcb4641c753658d/Assets/provisioners/demo-tasks/0.1.17/scripts/ansible/roles/domino-nomadweb/defaults/main.yml#L2-L3C1).  This is then used when checking the installer locations ([example](https://github.com/Moonshine-IDE/Super.Human.Installer/blob/019e59572e7a3f615f136b69cfcb4641c753658d/Assets/provisioners/demo-tasks/0.1.17/scripts/ansible/roles/domino-nomadweb/tasks/main.yml#L23)).

```
nomadweb_archive: nomad-server-1.0.6-for-domino-1202-linux.tgz
nomadweb_version: 1.0.6
```

We discussed this with @MarkProminic, and his intention was to allow this to be overridden in Hosts.yml.  In order to do this, we need to set values for the above properties in the [`vars` section](https://github.com/Moonshine-IDE/Super.Human.Installer/blob/019e59572e7a3f615f136b69cfcb4641c753658d/Assets/provisioners/demo-tasks/0.1.17/templates/Hosts.template.yml#L102-L117).  For example:

```
    vars:
      ...
      debug_all: true
      # change nomad version
      nomadweb_archive: ::NOMAD_INSTALLER::
      nomadweb_version: ::NOMAD_VERSION::
```

The Haxe code would need to be updated to replace the new insertion parameters `::NOMAD_INSTALLER::` `::NOMAD_VERSION::`.  The installer name would be determined by the file selected by the user.  The version would need to be parsed from the filename, defaulting to value like "UNKNOWN" if it can't be parsed.  For the Nomad example, the version is only used in labels, so it doesn't matter.  In theory we could need custom logic for different installer versions, though.

Note that this same issue will likely trigger for the other user-provided installers, so we would need to update the template with the appropriate properties for each installer.

**Comment by JoelProminic** [comment]
@MarkProminic noted that if we can confirm that the user selected the expected version of Nomad, we could exclude the variable overrides.  In that case, we could handle the variables like this, where `::NOMAD_VARS::` could be replaced by any empty string or the above properties:

```
    vars:
      ...
      debug_all: true
      ::NOMAD_VARS::
```

In my opinion, this solution seems unnecessarily complicated.  I think it is better to just always write the installer and version properties, like I showed above.

**Comment by piotrzarzycki21** [comment]
@MarkProminic @JoelProminic I have figure out on SHI what to change to apply installers picked up by the user. In order to test it I have changed locally my demo tasks 0.1.17 - everything worked nicely. Please check my properties based on screenshot. The question right now is where changes in demo-tasks should take place - should it be as part of next version 0.1.18 or still 0.1.17 ? I'm assuming all of these changes should be done by you Mark in your repository ?

List of files which has been changed locally:
<img width="1592" alt="Screenshot 2023-06-30 at 13 15 02" src="https://github.com/Moonshine-IDE/Super.Human.Installer/assets/24554795/66fa3362-ffb3-4dd7-95a4-e73df82957c1">

**Comment by piotrzarzycki21** [comment]
Additionally I didn't bother about versions of each installer - what was hardcoded stays as it was. I'm not sure how to resolve problems with passing the right version, because user pickup file and there is no other option. I can of course read name of the files and try to extract version, but it won't be too perfect.

**Comment by piotrzarzycki21** [comment]
The next step would for me take care of Hotfix and Fixpack for Domino - I think I need to have more discussion with Mark what properties need to be updated, but this can be for the laters work.

**Comment by MarkProminic** [comment]
@JoelProminic  Correct me if I mis-remember our conversation from the other day, but like I mentioned in [issue 77](https://github.com/Moonshine-IDE/Super.Human.Installer/issues/77), I was going to take the current [hosts.template.yml](https://github.com/Moonshine-IDE/Super.Human.Installer/blob/master/Assets/provisioners/demo-tasks/0.1.17/templates/Hosts.template.yml) that is in SHI, and copy it over to my repo, and begin to fill out the "[vars:](https://github.com/DominoVagrant/demo-tasks/blob/9315d44a40a129f03050aaf6f8151a4dd9c55047/Hosts.yml#L103)" section, with the variables in the format below. I believe this is the preferred format you wanted this in:

```
    vars:
      ...
      debug_all: true
      # change nomad version
      nomadweb_archive: ::NOMAD_INSTALLER::
      nomadweb_version: ::NOMAD_VERSION::
```

One question I have, is if I expose a new variable, ie a new Domino Project comes along, and I try something like this:

```
    vars:
      ...
      debug_all: true
      # change nomad version
      nomadweb_archive: ::NOMAD_INSTALLER::
      nomadweb_version: ::NOMAD_VERSION::
      # change domino project x
      domprojx_archive: ::DOMPROJX_INSTALLER::
      domprojx_version: ::DOMPROJX_VERSION::
```

Whether or not Haxe will have an issue with the interpolation of a undefined variable. If we can set that behavior to always write space or nothing, the default variables I define in the roles would takeover. So if someone can confirm that behavior and if its modifiable that will mean that there will be no need to manually transcribe new features and changes into Hosts.template.yml
